//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildersApp_Novikov_3ISP11_13.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int IdOrderService { get; set; }
        public int IdService { get; set; }
        public int IdClient { get; set; }
        public int IdPayment { get; set; }
        public int IdEmployee { get; set; }
        public int IdOrderStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PerformanceDate { get; set; }
        public string Commentary { get; set; }
        public int IdDeleted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Deleted Deleted { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Service Service { get; set; }
    }
}
