//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildersApp_Novikov_3ISP11_13.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComponent
    {
        public int IdOrderComponent { get; set; }
        public int IdClient { get; set; }
        public int IdComponent { get; set; }
        public int Quantity { get; set; }
        public int IdPayment { get; set; }
        public int IdEmployee { get; set; }
        public int IdOrderStatus { get; set; }
        public int IdSupplierType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime PerformanceDate { get; set; }
        public string Commentary { get; set; }
        public Nullable<int> IdDeleted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Component Component { get; set; }
        public virtual Deleted Deleted { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual SupplierType SupplierType { get; set; }
    }
}
