//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildersApp_Novikov_3ISP11_13.Helper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public Nullable<int> IdClient { get; set; }
        public Nullable<int> IdComponent { get; set; }
        public Nullable<int> IdService { get; set; }
        public Nullable<int> IdPayment { get; set; }
        public Nullable<int> IdSupplier { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DateOfSupply { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Component Component { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Service Service { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
